/*
 * UndoEvent.java
 *
 * Copyright (C) 2006  Yann D'ISANTO
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

package lunasql.ui.undo;

import java.awt.event.ActionEvent;
import java.util.EventObject;

/**
 * This high-level event is generated by a undo or redo <code>Action</code>. 
 * @author Yann D'ISANTO
 * @version 1.0.0 27/10/2006
 * @see UndoListener
 */
public class UndoEvent extends EventObject {
    private static final long serialVersionUID = 1222031350L;
    
    public static final int UNDO = 0;
    public static final int REDO = 1;
    
    private int type;
    
    /** Creates a new instance of <code>UndoEvent</code>.
     * @param e <code>ActionEvent</code> that generate the <code>UndoEvent</code>.
     * @param type <code>UndoEvent.UNDO</code> if this <code>UndoEvent</code> has 
     * been generated by an undo <code>Action</code> and Undo.REDO if it has 
     * been generated by an redo <code>Action</code>.
     */
    public UndoEvent(ActionEvent e, int type) {
        super(e.getSource());
        this.type = type;
    }
    
    /**
     * Returns <code>UndoEvent.UNDO</code> if this <code>UndoEvent</code> has 
     * been generated by an undo <code>Action</code> and Undo.REDO if it has 
     * been generated by an redo <code>Action</code>.
     * @return <code>UndoEvent.UNDO</code> if this <code>UndoEvent</code> has 
     * been generated by an undo <code>Action</code> and Undo.REDO if it has 
     * been generated by an redo <code>Action</code>.
     */
    public int getType() {
        return type;
    }
    
}
